version: '3.1'

services:
  api:
    image: ${ECR_IMAGE}:dev
    container_name: borderlands-fastapi-dev
    environment:
      - BORDERLANDS_ENCRYPTION_KEY=${BORDERLANDS_ENCRYPTION_KEY}
      - GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}
      - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
      - TWITTER_ACCESS_TOKEN_SECRET=${TWITTER_ACCESS_TOKEN_SECRET}
      - TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
      - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
    volumes:
      - "./borderlands_codes.db:/app/borderlands_codes.db"
    restart: unless-stopped
    ports:
      - 8081:8000
